### ISSUE TITLE
Game of zones strategy

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/EnigmaBlockchain#121]
Discuss how Enigma testnet can be a part of Game of Zones. Development team + validator community involvement

**Comment by jlwaugh** [comment]
instructions for joining the testnet to prepare for GoZ: https://github.com/iqlusioninc/relayer/tree/master/testnets

**Comment by cankisagun** [comment]
To-do:
Need to understand how long it takes for a Cosmos SDK chain to become available for IBC.
Can to ask Jack Z. @jlwaugh you can help me as well

**Comment by cankisagun** [comment]
Closing this issue as GoZ participation has passed
