### ISSUE TITLE
adding contributors to sprints?

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/EnigmaBlockchain#124]
I don't seem to be able to assign anyone outside of enigma to issues that are opened in this repo. Can we modify this? any reason not to? Tagging @assafmo because I think you're admin in this now. Not urgent. :)!

**Comment by lacabra** [comment]
@ainsleys you have to add those users as "Outside Collaborators" to the github enigmampc organization first. As long as these collaborators don't require access to any of Enigma's private repositories, we won't incur in any additional charges.

See: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization. When adding "Outside Collaborators" this way, grant them the `Triage` level of permissions.

**Comment by lacabra** [comment]
@ainsleys: one more thing, you do have `admin` privileges to this one repo, so you should be able to add Outside Collaborators.

**Comment by ainsleys** [comment]
thank you @lacabra for the explanation! Closing this for now as I understand what is required. 🙏
