### ISSUE TITLE
Add gas metering injection to wasm binaries

### ISSUE THREAD

**Issue by toml01** [enigmampc/EnigmaBlockchain#128]
- [x] Add gas injection to our wasmi module
- [x] Pass gas limit from the tx to our wasmi module
- [x] Enforce gas limit while executing WASM code
- [x] Return `used_gas` after the invocation

Possible references:
* https://github.com/paritytech/polkadot/blob/b7b4cc7720162a409f7ca46bfabbac06687090fc/substrate/runtime/contract/src/lib.rs#L370-L382
* https://github.com/enigmampc/enigma-core/blob/develop/enigma-runtime-t/src/lib.rs
* https://github.com/enigmampc/enigma-core/blob/develop/enigma-runtime-t/src/wasm_execution.rs

**Comment by assafmo** [comment]
We need to implement a function that the WASM code can call:
https://github.com/enigmampc/enigma-core/blob/2544d51ec87e42afb836631f0e5872fdbf395f08/enigma-runtime-t/src/lib.rs#L324-L327

**Comment by assafmo** [comment]
We need to dive further in this code: https://github.com/enigmampc/enigma-core/blob/2544d51ec87e42afb836631f0e5872fdbf395f08/enigma-runtime-t/src/lib.rs#L335-L359
And better understand this: https://docs.rs/pwasm-utils/0.12.0/pwasm_utils/fn.inject_gas_counter.html
