### ISSUE TITLE
Fix return value from enclave is wrong

### ISSUE THREAD

**Issue by assafmo** [enigmampc/EnigmaBlockchain#131]
@dingelish I'm trying to do a simple ecall that just returns a number, but I'm getting the wrong number:
Enclave.edl: https://github.com/enigmampc/wasmi-in-enclave-test/blob/d11d6998215b7ac5591b24cc2a2563ba66ce31fe/samplecode/hello-wasmi/enclave/Enclave.edl#L28
```
public size_t foo();
```
Trusted function implementation: https://github.com/enigmampc/wasmi-in-enclave-test/blob/d11d6998215b7ac5591b24cc2a2563ba66ce31fe/samplecode/hello-wasmi/enclave/src/lib.rs#L51-L54
```
#[no_mangle]
pub extern "C" fn foo() -> usize {
    123_usize
}
```
Declaration from userspace: https://github.com/enigmampc/wasmi-in-enclave-test/blob/d11d6998215b7ac5591b24cc2a2563ba66ce31fe/samplecode/hello-wasmi/app/src/main.rs#L33
```
extern "C" fn foo() -> usize;
```
Usage from userspace: https://github.com/enigmampc/wasmi-in-enclave-test/blob/d11d6998215b7ac5591b24cc2a2563ba66ce31fe/samplecode/hello-wasmi/app/src/main.rs#L98-L99
```
let x = unsafe { foo() };
println!("x == {} (should be 123)", x);
```
But I'm getting `8194` instead of `123` in x...
Any idea as to what the problem might be? :pray:

See https://gitter.im/rust-sgx-sdk/community?at=5e7a325f280fce2455003e81

**Comment by dingelish** [comment]
hi @assafmo , sorry for the late reply.

first is the EDL definition. As you defined an ECALL `public size_t foo();` I think ED should be 

```
    trusted {
        /* define ECALLs here. */
        public sgx_status_t say_something([in, size=len] const uint8_t* some_string, size_t len);
        public uint64_t foo();
    };
```

in untrusted app, the definition is:

```
extern "C" {
    fn foo(
        eid: sgx_enclave_id_t,
        retval: *mut u64,
    ) -> sgx_status_t;
}
```

**Comment by assafmo** [comment]
@dingelish A trusted function can only return `sgx_status_t`? Nothing else?

**Comment by assafmo** [comment]
Why is that? How can I know what to pass as `sgx_enclave_id_t`?

**Comment by toml01** [comment]
@dingelish and how can the signatures be different?
Why in the EDL there are no arguments and return value of `uint64_t`, and in the untrusted app its different?

**Comment by dingelish** [comment]
> Why is that? How can I know what to pass as `sgx_enclave_id_t`?

sgx_enclave_id_t is the id of enclave instance. After you create an enclave successfully, you can use `enclave.geteid()` to get that value. Reference: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/samplecode/hello-rust/app/src/main.rs#L60

**Comment by dingelish** [comment]
> @dingelish and how can the signatures be different?
> Why in the EDL there are no arguments and return value of `uint64_t`, and in the untrusted app its different?

let's assume the trusted function signature is `fn foo(arg: u32) -> u32`. then
Intel SGX toolchain will decorate it as:
```
fn foo(eid: sgx_enclave_id_t, retval: *mut 32, arg: u32) -> sgx_status_t
```

where
- sgx_enclave_id_t is used to specify which enclave you wanna dial in
- retval: the location where you wanna store your return value
- arg: the real arg
- ret value: whether or not the ECALL is done or it's error code

for example, if the return value (sgx_status_t) is 8194, which is 0x2002 = SGX_ERROR_INVALID_ENCLAVE_ID, it means the enclave id is not valid or say the system cannot find the enclave you wanna dial in

**Comment by assafmo** [comment]
So always in the untrusted code when we declare a trusted function the first 2 params are `eid` and `retval` and then the rest of the params which were defined in the EDL. And the return value is always `sgx_enclave_id_t`?

**Comment by dingelish** [comment]
> So always in the untrusted code when we declare a trusted function the first 2 params are `eid` and `retval` and then the rest of the params which were defined in the EDL. And the return value is always `sgx_enclave_id_t`?

you're right. i'll quickly impl this in my own fork. give me acouple of minutes!

**Comment by dingelish** [comment]
@assafmo @toml01 
Please see my demo
https://github.com/dingelish/teaclave-sgx-sdk/commit/30db972f062b80837090864831dd2774cd4094e3

**Comment by assafmo** [comment]
Thank you @dingelish!

**Comment by assafmo** [comment]
@dingelish Is `ocall`s the same just without `eid: sgx_enclave_id_t`?

**Comment by assafmo** [comment]
@dingelish when the ecall returns `void`, what should `retval` be?
