### ISSUE TITLE
Installing inside ubuntu container fails

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/EnigmaBlockchain#14]
When trying to install inside a docker container (ubuntu:18.04) (`RUN dpkg -i enigmachain_0.0.2_amd64.deb`) a few errors are encountered:

- logname: no login name
- `/var/lib/dpkg/info/enigmachain.postinst: line 23: sudo: command not found`

**Comment by assafmo** [comment]
Yeah, do not install the `.deb` file inside of docker. Extract `enigmad` from the `.deb` file and use it directly.

The deb file only copies `enigmad` and `enigmacli` to $PATH and sets `enigmad` as a systemd unit: https://github.com/enigmampc/enigmachain/blob/e559868c5e3fc39d278864c22d4aadef9ef9ca43/packaging_ubuntu/postinst
(This is where the `logname` is coming from, and also the `sudo` there is probably unnecessary)
