### ISSUE TITLE
Recover from Secret Node hardware failure?

### ISSUE THREAD

**Issue by moonstash** [enigmampc/EnigmaBlockchain#154]
I understand that work is progressing in regards to validators becoming Secret Nodes with the addition of secret contracts on the Enigma mainnet. I'm opening this issue in hopes that there will be a way to easily recover a secret node from hardware failure. Whatever this process looks like my hope is it's as simple as using a seed to recover and doing a resync of the chain🤞🏾.

**Comment by guyz** [comment]
Thanks! We need to keep this in mind as we progress, so this is an important issue to pay attention to. Most likely, the first mainnet will allow any SGX-enabled node to fully sync as long as it can prove it's running a proper enclave. In that case, a validator, I'd expect, can just spin up new hardware, go through the bootstrap process and then resync nodes.

There's an open question about how fast this is, how it ties to the jailing period, and also how it relates to the Sentry infrastructure which I'm less familiar with. All of these are considerations to take into account.

**Comment by assafmo** [comment]
I believe it's going to be as easy as moving your validator's key to a new node, just like in this guide https://github.com/enigmampc/EnigmaBlockchain/blob/master/docs/validators-and-full-nodes/migrate-a-validator.md

(E.g. if you have a sentry node you can stop it for 2 seconds, copy your validator's key to it and starting it again)

**Comment by assafmo** [comment]
Anyway the migration guide will be updated accordingly once needed.
