### ISSUE TITLE
[BUG] LCD SSL cert causing errors

### ISSUE THREAD

**Issue by dbriggsie** [enigmampc/EnigmaBlockchain#26]
Hi there,

I am running a seperate fullnode for RPC & LCD purposes

I have added in my SSL .crt & .key and even put them in the /config/ DIR & specified them in the config.toml
(My cert is from a CA - Comodo)

However it seems when there is a value in the cert & key options in the config I get no response on LCD from the https... and on http side i get this error.

http error:
{"error":"Status: error unmarshalling: invalid character 'C' looking for beginning of value"}

you can see on these two links it being reproduced.
https://172.105.11.162/node_info
http://172.105.11.162/node_info

Any info on this would be good. The reason i need SSL working is for swagger to connect over https. As its giving errors because it doesnt want to go from https -> http (lcd)

The SSL works fine for RPC, just not LCD..

**Comment by assafmo** [comment]
Closing because @dbriggsie sent me a DM that he went around the issue and used Nginx. This is a bug in Tendermint.
