### ISSUE TITLE
Deploy a public testnet with a faucet

### ISSUE THREAD

**Issue by assafmo** [enigmampc/EnigmaBlockchain#34]
- [x] Deploy faucet service
- [x] Register domain names for faucet and bootstrap nodes (with help of @lacabra )
- [x] Set up SSL certs
- [x] Create a new reCaptcha keys
- [x] Change to `test` keyring backend ~~Change password to faucet account~~
- [x] Update all in `.env` and `.env.local`
- [x] Fix README and clean comments etc.
- [x] Update dependencies to fix security vulnerabilities 
- [x] Upgrade to v0.1.0
- [x] Write blog post

**Comment by TomL94** [comment]
Waiting for @lacabra to help with a domain name.
