### ISSUE TITLE
Integrate (public) wasmd/CosmWasm into Enigma Blockchain

### ISSUE THREAD

**Issue by guyz** [enigmampc/EnigmaBlockchain#36]
- [x] Fork `cosmwasm/wasmd`, `confio/cosmwasm` & `confio/go-cosmwasm`
- [x] Init `wasmd` as a module in our app
- [x] Bump to v0.7.0
- [x] Test simple deploy & execute
- [x] Rename module from "wasm"
- [x] Create a pre-release for testnet

**Comment by assafmo** [comment]
Being done in the `cosmwasm` branch.
https://github.com/enigmampc/EnigmaBlockchain/tree/cosmwasm

**Comment by assafmo** [comment]
https://github.com/enigmampc/EnigmaBlockchain/tree/v0.1.0

**Comment by assafmo** [comment]
https://stackoverflow.com/questions/16747021/how-do-you-statically-link-a-c-library-in-go-using-cgo

**Comment by assafmo** [comment]
https://blog.madewithdrew.com/post/statically-linking-c-to-go/

**Comment by assafmo** [comment]
https://github.com/enigmampc/EnigmaBlockchain/releases/tag/v0.1.0
