### ISSUE TITLE
On-chain bootstrap skeleton

### ISSUE THREAD

**Issue by guyz** [enigmampc/EnigmaBlockchain#42]
This task sets the outline/interface of the bootstrap module. It should achieve the following:
- Have a _registered validators_ key-value store. It should allow validators to be in one of (pending, registered) states
- Have a register_validator() tx handler to deal with new validators who join in
- Have a share_seed() tx handler to deal with the sharing of the encrypted seed value for a new validator
- Have a confirm_validator() tx handler to change a new validator from 'pending' state to confirmed state

**Comment by assafmo** [comment]
In [`InitChainer`](https://github.com/enigmampc/EnigmaBlockchain/blob/94fd38b45d1c6a499e98157dd0be09c2fd5878df/app.go#L404-L410) a node should check whether they're the first node and if so then call `ecall_bootstrap` (better name TBD) which runs the [bootstrap protocol](https://forum.enigma.co/t/network-key-management-agreement/1324) and returns encrypted "registration values" to be recorded on-chain.

**Comment by guyz** [comment]
@assafmo yes - there's an issue for that - https://github.com/enigmampc/EnigmaBlockchain/issues/43

**Comment by assafmo** [comment]
Cool, missed it

**Comment by assafmo** [comment]
Became part of #43
