### ISSUE TITLE
Manage the lifecycle of new nodes

### ISSUE THREAD

**Issue by guyz** [enigmampc/EnigmaBlockchain#43]
New nodes should not be able to start syncing blocks UNTIL they are confirmed as a registered node. We should look into `InitChainer` and `EndBlocker`.

### New node

- [x] register node
  - [x] generate report for enclave
[Get quote - SafeTrace ref](https://github.com/enigmampc/SafeTrace/blob/master/enclave/safetrace/app/src/networking/ipc_listener.rs#L97-L122)
  - [x] using `enigmad` generate key pair inside of the enclave
  - [x] seal + backup private key
  - [x] handle loading of private key on node init
  - [x] using IAS (proxy node) get report for public key (signed quote)
  - [x] `enigmacli` send tx with public key as a param + report
  - [x] bootstrap node handling (only happens for the first node)
        Initialization logic for the enclave. See the logic described here in Phase 1 (register_node()): https://forum.enigma.co/t/network-key-management-agreement/1324
        Check whether this can happen automatically inside the global `InitChainer` (also whether this can listen to new blocks and block execution until the new node is confirmed).

### Existing nodes

- [x] confirm node
  - [x] get `register_node()` tx
  - [x] pass `(new_node_public_key, report)` to the enclave
  - [x] verify report locally (using hard coded intel's pub key)
[Discovery ref #1](https://github.com/enigmampc/enigma-contract/blob/master/contracts/impl/WorkersImpl.sol)
[Discovery ref #2](https://github.com/enigmampc/enigma-contract/blob/master/contracts/utils/SolRsaVerify.sol)
  - [x] take `sk_io` with `new_node_public_key` and derive a new symmetric key (using `derive_key` https://forum.enigma.co/t/input-output-state-encryption-decryption-protocol/1325)
  - [x] encrypt `seed` with the new symmetric key from the previous step
  - [x] return from the enclave with the encrypted seed
  - [x] write the encrypted seed to chain
        Initialization logic for the enclave. See the logic described here in Phases 2+3: https://forum.enigma.co/t/network-key-management-agreement/1324

### New node again

- [x] `register_node()`
  - [x] decrypt seed with `pk_io` and my private key (using `derive_key` https://forum.enigma.co/t/input-output-state-encryption-decryption-protocol/1325). With the single shared 256-bit seed generated above, we can run the CSPRNG several times to get other 256-bit pseudo-random keys:
  - [x] First 256 bits: used to generate (`sk_io`, `pk_io`) --> a key pair whose pubkey can be used by users to derive new symmetric encryption keys for encrypting input/outputs. The protocol above needs to be changed so that the first validator also broadcasts `pk_io` to the network.
  - [x] Next 256 bits: used to generate `master_state_key` --> a symmetric key used to encrypt contract state. In practice, this is a seed we can use to derive further keys.
  - [x] Next 256 bits: used to generate `master_iv` --> this is a seed that can be used to generate fresh IVs for encrypting outputs. That’s how the network can avoid non-determinism and still maintain the security of symmetric ciphers.
  - [x] Next 256 bits: used to generate `master_rand_seed` --> this is a seed that can be used to generate randomness.
  - [x] check how to pass this to my `InitChainer` to be able to sync blocks

**Comment by assafmo** [comment]
In [`InitChainer`](https://github.com/enigmampc/EnigmaBlockchain/blob/94fd38b45d1c6a499e98157dd0be09c2fd5878df/app.go#L404-L410) a node should check whether they're the first node and if so then call `ecall_bootstrap` (better name TBD) which runs the [bootstrap protocol](https://forum.enigma.co/t/network-key-management-agreement/1324) and returns encrypted "registration values" to be recorded on-chain.

**Comment by assafmo** [comment]
From https://forum.enigma.co/t/network-key-management-agreement/1324:

> 1. When the first validator joins in, they need to look at the blockchain’s state and determine that there are no existing registered validators.
> 
> 2. In the enclave, call register_validator(first_validator=True). The code does the following steps:
> 
> sk_v := rand() // generate a 256-bit secret key for this validator
> pk_v := sk_v*G // generate the corresponding public key
> seal(sk_v, pk_v) // persist this key pair locally, encrypted using the enclave’s hardware key
> seed := rand() // generate a 256-bit master seed
> seal(seed) // persists locally
> return (pk_v, remote_attestation_quote)

This should always happen for each node in InitChainer.

**Comment by assafmo** [comment]
> 3. Outside of the enclave, the validator should send the quote to Intel’s Attestation Service (IAS) - potentially through Enigma’s proxy as was the case with Discovery, and get a signed report.

We need to check whether this can happen offline.

**Comment by assafmo** [comment]
> 4. Broadcast a register_validator(pk_v, report) transaction.

I'm not sure this is still needed, as we decided the at first all nodes will share the master key, so after the initial node registration becoming a validator is the same as in a vanilla tendermint chain.

**Comment by assafmo** [comment]
> 5. On-chain: check that the report is valid on-chain. If it is, and because there are no other validators, immediately approve this validator.

Also isn't needed anymore :point_up:

**Comment by assafmo** [comment]
> Any registered validator can see the pending validator’s request on chain. Let’s say the pending validator is called v2 and the registered validator is called v1. v1 should then call share_key(pk_v2, report)

This might be done [in the `EndBlocker`](https://github.com/enigmampc/EnigmaBlockchain/blob/94fd38b45d1c6a499e98157dd0be09c2fd5878df/app.go#L394-L397) and be part of the consensus. WIll be a much better UX.
