### ISSUE TITLE
Client library to deploy WASM contracts

### ISSUE THREAD

**Issue by guyz** [enigmampc/EnigmaBlockchain#55]
Experiment with CosmWasm client library. Integrate into our own tools. NOTE: this is subject to have breaking changes, so we should not spend too much time here right now.

**Comment by guyz** [comment]
Lower priority - will have breaking changes anyway. We'll use the CLI for now.

**Comment by assafmo** [comment]
https://medium.com/confio/introduction-to-cosmwasm-js-548f58d9f6af

**Comment by assafmo** [comment]
https://github.com/confio/cosmwasm-js

**Comment by assafmo** [comment]
> We'll use the CLI for now.
