### ISSUE TITLE
gen_keys() function (in the Enclave)

### ISSUE THREAD

**Issue by guyz** [enigmampc/EnigmaBlockchain#56]
Used to generate the following initial keys once the seed is shared:
- (sk_io, pk_io) --> shared key for deriving input/output keys. pk_io is available on-chain, and sk_io is shared across all validators’ enclaves.
- master_state_key --> a symmetric master key used to derive other state keys.
- master_iv --> an IV seed used to generate fresh pseudo-random IVs for both encrypted outputs and state encryption.

https://forum.enigma.co/t/network-key-management-agreement/1324

**Comment by assafmo** [comment]
Inlined in #43
