### ISSUE TITLE
enigmacli query on slashing for validator is returning "null"

### ISSUE THREAD

**Issue by lauraweindorf** [enigmampc/EnigmaBlockchain#60]
Using the following command is supposed to display slashing info for a validator:

enigmacli q distribution slashes [validator-operator-address] [start-height] [end-height]

I tried with an `enigmavaloper1...`  address that had a slashing event, but the command is returning:

```
null
```

**Comment by assafmo** [comment]
What was the exact command?

**Comment by lauraweindorf** [comment]
I used this command:

 `enigmacli q distribution slashes
      enigmavaloper1qjk5uduu3zg356chmstcp2eqgdn35jp34ckqqk 107000 111000`

**Comment by assafmo** [comment]
According to the "Power Change" view in https://explorer.scrt.cashmaney.com/validator/enigmavaloper1qjk5uduu3zg356chmstcp2eqgdn35jp34ckqqk the slashing was in block 190,000, but this command works for me:
```
➜  ~ enigmacli q distribution slashes enigmavaloper1qjk5uduu3zg356chmstcp2eqgdn35jp34ckqqk 189998 189998
[
  {
    "validator_period": "21",
    "fraction": "0.009999909355636774"
  }
]
```
So maybe it was in 189,998? Anyway your original range of 107,000->111,000 didn't include any slashing for this validator so `null` is a correct output.

**Comment by lauraweindorf** [comment]
Oh, I'm sorry @assafmo! I got the blocks wrong. I originally tried with 1 and 200,000 and got "null" but I must've typed something else wrong.

Thanks!!
