### ISSUE TITLE
How to remove a validator

### ISSUE THREAD

**Issue by lacabra** [enigmampc/EnigmaBlockchain#62]
While there is documentation on how to join a network as a validator, I have not been able to find information on how to properly stop being a validator. I would like to request adding the proper documentation for it.

**Comment by assafmo** [comment]
Yeah I also haven't seen anything related in the cosmos docs. I guess you can redelegate to another validator and just let the node die, but I don't like this solution.

**Comment by assafmo** [comment]
I asked cosmos, they are saying that when the self-delagator account redelegates from the validator, all other delegators start to unbond.
I'll try to find docs in other cosmos based projects.

**Comment by assafmo** [comment]
6e236f6437e22cb7e3e3fc33faa3473adab1587c

**Comment by assafmo** [comment]
![Screenshot from 2020-03-09 15-54-01](https://user-images.githubusercontent.com/22766533/76219273-3ff84e80-621e-11ea-82c7-bd740a2fac81.png)
