### ISSUE TITLE
Testnet index txs

### ISSUE THREAD

**Issue by assafmo** [enigmampc/EnigmaBlockchain#77]
Follow this thread https://forum.enigma.co/t/testnet-is-live-with-smart-contracts/1386/13

**Comment by toml01** [comment]
This occurs on mainnet and testnet..
I suspect it's a bug with cosmos-sdk, as idexing seems to be `on` (http://bootstrap.testnet.enigma.co/node_info) and we can query a specific tx (e.g. http://bootstrap.testnet.enigma.co/txs/E8D4CD179287B62CFE47A798EF8BAD010E278F97A372E84A25FE12993767E30A)

**Comment by assafmo** [comment]
https://forum.enigma.co/t/testnet-is-live-with-smart-contracts/1386/32
