### ISSUE TITLE
Write docs on using gov

### ISSUE THREAD

**Issue by assafmo** [enigmampc/EnigmaBlockchain#8]
Write docs on using the governance module:
1. How to create proposals
2. How to deposit
3. Deposits burn risk
4. How to vote, modify a vote and validator/delegator dynamic

**Comment by ainsleys** [comment]
This would be great, as @jlwaugh is working on a nontechnical summary of these right now. and we've entered voting for a first proposal!

Currently only the ledger guide has voting info: 
`enigmacli tx gov vote <proposal-id> <vote> --from <account name> --ledger
`

Im assuming one can just remove the ledger flag and it will work with other setups. 
I am also assuming the <vote> can be any of these: 
`Yes
No`
but am not sure if we also include these or other options:
`NoWithVeto
Abstain`

**Comment by assafmo** [comment]
@ainsleys Yes, you can remove the ledger flag if you aren't using ledger. This is the message I sent on TG: 
Hi, guys!
So we have our first proposal already which is very exciting :tada: (at least to me :heart_eyes:)
You can see the proposal here: https://explorer.mainnet.enigma.co/proposals/1

It is now in a deposit stage of 1 week (until 2020-02-22 20:26:56 UTC). In order for a proposal to be considered for voting, it must reach a minimum deposit of 1000 SCRT. The deposit mechanism is sort of a spam filter for proposals.
Dan from ChainofSecrets.org had already deposited 2 SCRT so it has 998 more to go.
If the proposal won't reach a deposit of 1000 SCRT by 2020-02-22 20:26:56 UTC then everyone gets their deposit back.

The only ways deposits won't be returned to their owner is:
1. If in the voting period the proposal gets 33.4% `NoWithVeto` out of all votes, excluding `Abstain` votes (So `NoWithVeto` needs to be 33.4% out of all `Yes`, `No` & `NoWithVeto`).
2. If in the voting period less than 33.4% of voting power votes (== The proposal won't reach a quorum).

To deposit 100 SCRT for this proposal one would run:
```
enigmacli tx gov deposit 1 100000000uscrt --from mykey
```
(1 is the proposal id)

Anyone can deposit for a proposal, even if you have 0 uSCRT tokens staked/delegated/bonded.

If the proposal reaches 1000 SCRT deposit before 2020-02-22 20:26:56 UTC then it enters a voting period of 1 week.
Validators and delegators could then vote on this proposal like this:
```
enigmacli tx gov vote 1 <yes|no|not_with_veto|abstain> --from mykey
```
(Again, 1 is the proposal id)
You can change your vote by sending another `enigmacli tx gov vote` with a different value.
By default validator gets their delegators voting power. Delegators can vote to override their validators' votes. Voting order doesn't matter in this validator/delegator dynamic.

In order for a proposal outcome to be valid, 33.4% of all voting power ( == bonded tokens == staked+delegated tokens) must vote `Yes`, `No`, `NoWithVeto` or `Abstain` (== reach quorum).

In order for a proposal to be accepted, 50% of all `Yes`, `No` & `NoWithVeto` votes must be Yes.

**Comment by assafmo** [comment]
01e19751d81f18e4e2676dd11fc8f7b9aa7870b5
