### ISSUE TITLE
error decoding 'consensus.create_empty_blocks_interval': time: invalid duration

### ISSUE THREAD

**Issue by levackt** [enigmampc/EnigmaBlockchain#81]
> > error decoding 'consensus.create_empty_blocks_interval': time: invalid duration
@Derek I just joined this group to ask the same question. I am seeing the same error.
> This happens here -

>sudo systemctl start enigma-node

>So the node never starts-up...
> I run on other cosmos-sdk networks and am quite familiar with them. I've never seen this error though. It just happened again on a fresh install.

This is from Chris in discord, Derek had/has the same problem but posted a new error copied below, can we ask for any config files or output to help troubleshoot? @assafmo 

>dialing failed (attempts: 12): dial tcp 198.74.53.44:26656: i/o timeout module=pex addr=4efa7d9

**Comment by assafmo** [comment]
https://discordapp.com/channels/360051864110235648/360167281491181569/686912626927861762

**Comment by assafmo** [comment]
Turns out it was connection issues to the kamut community operated testnet which was already dead

https://discordapp.com/channels/360051864110235648/360167281491181569/688841399679975437

**Comment by levackt** [comment]
Thanks for chasing it down Assaf, will prompt for config and check the seed etc next time

**Comment by assafmo** [comment]
:blush:
