### ISSUE TITLE
Error: unknown address: account .... (why?)

### ISSUE THREAD

**Issue by shiro-hh** [enigmampc/EnigmaBlockchain#82]
Hey i got the full node running.
As mainnet validator i always get a unknown adress error. 
This makes no sense (at least for me) i tried two different addresses to join the network both has scrt (kindly gifted from laura) but non of them is accepted... unknown adress account....
Has anyone run into the same problem ?

**Comment by realjohnward** [comment]
@shiro-hh Yes

**Comment by assafmo** [comment]
Can you elaborate more on this? 
Did you do https://github.com/enigmampc/EnigmaBlockchain/blob/master/docs/validators-and-full-nodes/join-validator-mainnet.md?
What's the output of your `journalctl -u enigma-node`?

**Comment by assafmo** [comment]
![Screenshot from 2020-03-11 10-37-25](https://user-images.githubusercontent.com/22766533/76397761-57e9e280-6384-11ea-96d0-90d3f2bf37a1.png)
