### ISSUE TITLE
Init cosmwasm-sgx-vm

### ISSUE THREAD

**Issue by assafmo** [enigmampc/EnigmaBlockchain#85]
- [x] Patch `go-cosmwasm` to use local dependencies
- [x] Copy `cosmwasm-vm` to a new directory containing the new wasmi+sgx code
- [x] Adjust `cosmwasm-sgx-vm` to call the enclave (`wasmi-runtime`) instead of using `wasmer`
- [x] Define the interface between `cosmwasm-sgx-vm` and the `wasmi-runtime`
    * The types in this interface are defined in `cosmwasm/lib/enclave-ffi-types` and have autogenerated C bindings. See the `.edl` file in `cosmwasm/lib/wasmi-runtime` to see how they are used.
- [x] Implement safe wrappers around the FFI on the `cosmwasm-sgx-vm` side
- [x] Write the `.edl` file describing the interface between the enclave and the outside world
- [x] Implement safe wrappers around the FFI on the `wasmi-runtime` side
- [x] Use `wasmi` to execute the wasm contracts in the environment they expect, as defined in `cosmwasm`

**Comment by reuvenpo** [comment]
related PR (WIP, most of the content is still only in my working directory): #122
