### ISSUE TITLE
uscrt required, but sends scrt

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/EnigmaBlockchain#86]
https://github.com/enigmampc/EnigmaBlockchain/compare/81bbf533564e...b82044567432

I modified the above, b/c the transaction doesn't work when using 10scrt. However, elsewhere in docs (i.e, for delegating), when uscrt is required you need to send the number in uscrt (i.e., 10000000uscrt). This could go badly if someone sees uscrt and sends in uscrt, because the actual transactions are denominated in scrt. 

We should probably understand why this is / if we can be consistent....

**Comment by ainsleys** [comment]
nevermind. It does require uscrt, but does in fact send uscrt.

**Comment by assafmo** [comment]
was is scrt in the doc instead of uscrt?

**Comment by ainsleys** [comment]
yup, that's what i changed

**Comment by assafmo** [comment]
Thanks!
