### ISSUE TITLE
Error: Invalid argument error when starting enigma-node via systemctl

### ISSUE THREAD

**Issue by lauraweindorf** [enigmampc/EnigmaBlockchain#87]
[from @baedrik]:

Trying to set up a node, but the service is logging that it exits with status 2/invalidargument.  When I look at the .service file, it starts as: "/bin/enigmad start" so I don't know what argument it might be referring to.  If I just run enigmad start instead of starting it as the systemd service, it runs fine.  Any idea why the service is failing?  Journactl does show a lot of messages that shows a path  of "/home/assafmo/workspace/..." Not sure if that has anything to do with it

cc @assafmo 

Waiting for more info (errors) and from @baedrik per Assaf's request:

What version of enigma are you using? v0.0.2?
Also could you paste here the content of /etc/systemd/system/enigma-node.service?

**Comment by lauraweindorf** [comment]
[from @baedrik]:
yes it is v0.0.2.  service file is 
```
[Unit]
Description=Enigma node service
After=network.target

[Service]
Type=simple
ExecStart=/bin/enigmad start
User=
Restart=always
StartLimitInterval=0
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
```
so really don't know what argument is being referred to in the journalctl
```
Mar 11 11:45:04 PrimaryNodes enigmad[154817]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:805 +0x56b
Mar 11 11:45:04 PrimaryNodes enigmad[154817]: github.com/spf13/cobra.(*Command).ExecuteC(0xc00013a280, 0x130dd5e, 0xc000483e90, 0x5905c2)
Mar 11 11:45:04 PrimaryNodes enigmad[154817]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
Mar 11 11:45:04 PrimaryNodes enigmad[154817]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 11 11:45:04 PrimaryNodes enigmad[154817]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
Mar 11 11:45:04 PrimaryNodes enigmad[154817]: github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00013a280, 0x1473308, 0x12f1401, 0x10)
Mar 11 11:45:04 PrimaryNodes enigmad[154817]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/libs/cli/setup.go:89 +0x3c
Mar 11 11:45:04 PrimaryNodes enigmad[154817]: main.main()
Mar 11 11:45:04 PrimaryNodes enigmad[154817]:         /home/assafmo/workspace/enigmachain/cmd/enigmad/main.go:69 +0x7ab
Mar 11 11:45:04 PrimaryNodes systemd[1]: enigma-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 11 11:45:04 PrimaryNodes systemd[1]: enigma-node.service: Failed with result 'exit-code'.
```
And as I mentioned, it WILL run if I manually start it from the console with "/bin/enigmad start"

**Comment by assafmo** [comment]
Thanks @lauraweindorf

**Comment by assafmo** [comment]
https://discordapp.com/channels/360051864110235648/360167281491181569/687376404714749965

**Comment by neocrash** [comment]
I can get the same log. But it WILL run if I manually start it from the console with "/user/local/bin/secretd start"

in /etc/systemd/system/secret-node.service 
[Unit]
Description=Secret node service
After=network.target

[Service]
Type=simple
Environment=SCRT_ENCLAVE_DIR=/usr/lib
WorkingDirectory=/root
ExecStart=/usr/local/bin/secretd start
User=
Restart=on-failure
StartLimitInterval=0
RestartSec=3
LimitNOFILE=65535
LimitMEMLOCK=209715200

[Install]
WantedBy=multi-user.target

**Comment by assafmo** [comment]
In the service file please fix the User parameter.

**Comment by esgei** [comment]
> In the service file please fix the User parameter.

Sorry to bother you.
Is it right : in service file add a accout name for User like this(User=root)

**Comment by assafmo** [comment]
Yes, but make sure that you use the user who installed the node.
