### ISSUE TITLE
Spawn enigma-testnet-2 or recover enigma-testnet

### ISSUE THREAD

**Issue by assafmo** [enigmampc/EnigmaBlockchain#97]
Related: #98, #96

If we're spawning a new testnet:
- [x] Document recovery
- [x] Spawn new nodes
- [x] ~~Spawn new faucet~~
- [x] Fix docs
- [x] ~~Fix domains~~
- [x] Tell cashmaney to point the explorer to enigma-testnet-2
- [x] Tell everyone

**Comment by toml01** [comment]
Waiting on that to see if we get some direction for the best way to recover from this situation.
My current suggestion is:
* Export state from height prior to param change
* Manually fix proposal
* Start chain from the fixed state

**Comment by assafmo** [comment]
What does it mean to manually fix the proposal?

**Comment by toml01** [comment]
We will export to a state before the proposal got passed. So we need to fix it or remove it entirely, so the parameter change won't happen again.

**Comment by assafmo** [comment]
So export before the proposal was created, or after and then vote against
it?

**Comment by toml01** [comment]
My thinking is to try not to impact the network as much as possible. (Say if it happens on mainnet, and in the voting period a bunch of txs happen. we preferably don't want them to disappear).
So I will try to just remove this proposal and see what happens.
